services:
  rpsd-commons:
    extends:
      file: ./docker-compose-base.yml
      service: rpsd-commons
    command: ["uv", "run", "--directory", "/workspaces/rpsd-commons", "app"]
    #command: /bin/sh -c "sleep 0s; echo 'PIPPO!!!'"

  ############################
  # Dapr sidecar
  ############################
  rpsd-commons-dapr:
    extends:
      file: ./docker-compose-base.yml
      service: rpsd-commons-dapr

############################
# Network between containers
############################
networks:
  rpsd-dapr:
    external: true
    name: rpsd-dapr
